# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3edbb0be8f924da016446a537be50e22422eaa8b9b563ee8d529759a76828442647186e2287a32eb3a3811c6d14b2fbb95bc34885e00c8b0c87bc0843b41cbc

test:
  secret_key_base: d4deb935999eeb0b2261840230af8533d7b76f0750d7c5bdad69b7ed1a9df6cecfe5f0c417222a200391431ad99acf5e62fff66b90877c89ffce00e4986f402b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
